apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - 'pgrep nginx && pgrep telegraf && pgrep php'
            initialDelaySeconds: 10
            periodSeconds: 5